<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\SIA.BuildingBlocks.Contracts\SIA.BuildingBlocks.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Clients\" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
