<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIA.SchoolControlService.Application\SIA.SchoolControlService.Application.csproj" />
    <ProjectReference Include="..\SIA.SchoolControlService.Infrastructure\SIA.SchoolControlService.Infrastructure.csproj" />
    <ProjectReference Include="..\SIA.SchoolControlService.Contracts\SIA.SchoolControlService.Contracts.csproj" />
  </ItemGroup>

</Project>
