<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SIA.TenancyService.Domain\SIA.TenancyService.Domain.csproj" />
    <ProjectReference Include="..\SIA.TenancyService.Contracts\SIA.TenancyService.Contracts.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\SIA.BuildingBlocks.Application\SIA.BuildingBlocks.Application.csproj" />
    <ProjectReference Include="..\..\..\building-blocks\SIA.BuildingBlocks.Domain\SIA.BuildingBlocks.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
