<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>f31deaca-a844-4516-b7ea-853120838e99</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIA.NotificationsService.Application\SIA.NotificationsService.Application.csproj" />
    <ProjectReference Include="..\SIA.NotificationsService.Infrastructure\SIA.NotificationsService.Infrastructure.csproj" />
    <ProjectReference Include="..\SIA.NotificationsService.Contracts\SIA.NotificationsService.Contracts.csproj" />
  </ItemGroup>

</Project>
