<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>88f238a0-014b-4497-a6da-b64982a929fb</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIA.WorkflowService.Application\SIA.WorkflowService.Application.csproj" />
    <ProjectReference Include="..\SIA.WorkflowService.Infrastructure\SIA.WorkflowService.Infrastructure.csproj" />
    <ProjectReference Include="..\SIA.WorkflowService.Contracts\SIA.WorkflowService.Contracts.csproj" />
  </ItemGroup>

</Project>
