<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>7006c4ab-c4fe-4a61-99e4-67ed0c2409cc</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\building-blocks\SIA.BuildingBlocks.Contracts\SIA.BuildingBlocks.Contracts.csproj" />
    <ProjectReference Include="..\..\building-blocks\SIA.BuildingBlocks.Observability\SIA.BuildingBlocks.Observability.csproj" />
  </ItemGroup>

</Project>
