<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>e995a1af-4171-4b52-a341-33455f54076d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SIA.IdentityService.Application\SIA.IdentityService.Application.csproj" />
    <ProjectReference Include="..\SIA.IdentityService.Infrastructure\SIA.IdentityService.Infrastructure.csproj" />
    <ProjectReference Include="..\SIA.IdentityService.Contracts\SIA.IdentityService.Contracts.csproj" />
  </ItemGroup>

</Project>
